### ISSUE TITLE
Division by zero error while calculating multi-anchor slider shape

### ISSUE THREAD

**Issue by Patipol-BKK** [Awlexus/python-osu-parser#7]
```
C:\Users\user\Desktop\beatmaps\test2\1000885 Roselia - MIIRO\Roselia - MIIRO (lit120) [lolia's Destroyer].osuTraceback (most recent call last):
  File "dataset_formatter.py", line 43, in <module>
    parser.build_beatmap()
  File "C:/Users/user/Documents/GitHub/python-osu-parser\beatmapparser.py", line 372, in build_beatmap
    self.parse_hit_object(object_line)
  File "C:/Users/user/Documents/GitHub/python-osu-parser\beatmapparser.py", line 232, in parse_hit_object
    hit_object["points"])
  File "C:/Users/user/Documents/GitHub/python-osu-parser\slidercalc.py", line 61, in get_end_point
    cx, cy, radius = get_circum_circle(p1, p2, p3)
  File "C:/Users/user/Documents/GitHub/python-osu-parser\slidercalc.py", line 122, in get_circum_circle
    ux = ((x1 * x1 + y1 * y1) * (y2 - y3) + (x2 * x2 + y2 * y2) * (y3 - y1) + (x3 * x3 + y3 * y3) * (y1 - y2)) / d
ZeroDivisionError: division by zero
```
Got the specific error while calculating this slider `00:00:512 (2)` from this [beatmap](https://osu.ppy.sh/beatmapsets/1000885#osu/2101692):
![image](https://user-images.githubusercontent.com/53873809/229383020-a94c340a-a20f-4ae9-9084-4afe9b6622aa.png)

**Comment by Zerqqc** [comment]
Do you know how to fix it?

**Comment by Zerqqc** [comment]
SOLUTION:
```
        if len(points) == 3 and points[1] == points[2]:
            return point_on_line(points[0], points[1], slider_length)
```
add this condition in `get_end_point` function along with other ones


```
elif slider_type == 'pass-through':
        if not points or len(points) < 2:
            return 'undefined'

        if len(points) == 3 and points[1] == points[2]:
            return point_on_line(points[0], points[1], slider_length)
        
        if len(points) == 2:
            return point_on_line(points[0], points[1], slider_length)

        if len(points) > 3:
            return get_end_point('bezier', slider_length, points)
```
